export const SAVE_CRYPTO_ACCOUNTS = 'app/Profile/SAVE_CRYPTO_ACCOUNTS';
export const SAVE_CRYPTO_ACCOUNTS_SUCCESS =
  'app/Profile/SAVE_CRYPTO_ACCOUNTS_SUCCESS';
export const SAVE_CRYPTO_ACCOUNTS_ERROR =
  'app/Profile/SAVE_CRYPTO_ACCOUNTS_ERROR';
