const REDIRECT_TO_ASK_QUESTION_PAGE =
  'app/AskQuestion/REDIRECT_TO_ASK_QUESTION_PAGE';

const ASK_QUESTION = 'app/AskQuestion/ASK_QUESTION';
const ASK_QUESTION_SUCCESS = 'app/AskQuestion/ASK_QUESTION_SUCCESS';
const ASK_QUESTION_ERROR = 'app/AskQuestion/ASK_QUESTION_ERROR';

const GET_EXISTING_QUESTIONS =
  `app/AskQuestion/GET_EXISTING_QUESTIONS`;
const GET_EXISTING_QUESTIONS_SUCCESS =
  `app/AskQuestion/GET_EXISTING_QUESTIONS_SUCCESS`;
const GET_EXISTING_QUESTIONS_ERROR =
  `app/AskQuestion/GET_EXISTING_QUESTIONS_ERROR`;

const ASK_QUESTION_FORM = 'app/AskQuestion/ASK_QUESTION_FORM';
const POST_QUESTION_BUTTON = 'app_post_question_button';

const MIN_RATING_TO_POST_QUESTION = 0;
const MIN_ENERGY_TO_POST_QUESTION = 10;

export {
  REDIRECT_TO_ASK_QUESTION_PAGE,
  ASK_QUESTION,
  ASK_QUESTION_SUCCESS,
  ASK_QUESTION_ERROR,
  ASK_QUESTION_FORM,
  POST_QUESTION_BUTTON,
  MIN_RATING_TO_POST_QUESTION,
  MIN_ENERGY_TO_POST_QUESTION,
  GET_EXISTING_QUESTIONS,
  GET_EXISTING_QUESTIONS_SUCCESS,
  GET_EXISTING_QUESTIONS_ERROR,
};
