/*
 *
 * SignUp constants
 *
 */

export const EOS_ACC = 'app/SignUp/eosAccount';
export const DISPLAY_NAME = 'app/SignUp/displayName';

export const FETCH_REGISTER_ACC = 'app/SignUp/FETCH_REGISTER_ACC';
export const REGISTER_ACC_SUCCESS = 'app/SignUp/REGISTER_ACC_SUCCESS';
export const REGISTER_ACC_ERROR = 'app/SignUp/REGISTER_ACC_ERROR';
export const SET_REDUCER_DEFAULT = 'app/SignUp/SET_REDUCER_DEFAULT';

export const COMPLETE_SIGNUP = 'COMPLETE_SIGNUP';
export const SIGN_UP_MODAL_ID = 'SIGN_UP_MODAL_ID';
export const SHOW_SIGN_UP_MODAL = 'SHOW_SIGN_UP_MODAL';
export const HIDE_SIGN_UP_MODAL = 'HIDE_SIGN_UP_MODAL';

export const SHOW_DEFAULT_SIGNUP_MODAL = 'SHOW_DEFAULT_SIGNUP_MODAL';
export const USER_IS_ABSENT_IN_SYSTEM_AND_SIGNUP =
  'USER_IS_ABSENT_IN_SYSTEM_AND_SIGNUP';
export const USER_IS_ABSENT_IN_SYSTEM_AND_LOGIN =
  'USER_IS_ABSENT_IN_SYSTEM_AND_LOGIN';
export const NO_SELECTED_SCATTER_ACCOUNTS = 'NO_SELECTED_SCATTER_ACCOUNTS';
export const NO_SCATTER = 'NO_SCATTER';
