/*
 * SignUp Messages
 *
 * This contains all the text for the Sign component.
 */

import { defineMessages } from 'react-intl';
import {
  USER_ALREADY_REGISTERED_ERROR,
  USER_REJECTED_SIGNATURE_REQUEST_ERROR,
  USER_IS_NOT_SELECTED_ERROR,
} from './constants';

export default defineMessages({
  title: {
    id: 'app.containers.SignUp.title',
  },
  description: {
    id: 'app.containers.SignUp.description',
  },
  continue: {
    id: 'app.containers.SignUp.continue',
  },
  email: {
    id: 'app.containers.SignUp.email',
  },
  verificationCode: {
    id: 'app.containers.SignUp.verificationCode',
  },
  verify: {
    id: 'app.containers.SignUp.verify',
  },
  sendAnotherCode: {
    id: 'app.containers.SignUp.sendAnotherCode',
  },
  eosActivePrivateKey: {
    id: 'app.containers.SignUp.eosActivePrivateKey',
  },
  privateKey: {
    id: 'app.containers.SignUp.privateKey',
  },
  eosOwnerPrivateKey: {
    id: 'app.containers.SignUp.eosOwnerPrivateKey',
  },
  storeThisKey: {
    id: 'app.containers.SignUp.storeThisKey',
  },
  secretPhrase: {
    id: 'app.containers.SignUp.secretPhrase',
  },
  ethereumUserAddress: {
    id: 'app.containers.SignUp.ethereumUserAddress',
  },
  displayName: {
    id: 'app.containers.SignUp.displayName',
  },
  referralCode: {
    id: 'app.containers.SignUp.referralCode',
  },
  password: {
    id: 'app.containers.SignUp.password',
  },
  confirmPassword: {
    id: 'app.containers.SignUp.confirmPassword',
  },
  iSaveSecretPhrase: {
    id: 'app.containers.SignUp.iSaveSecretPhrase',
  },
  downloadSecretPhrase: {
    id: 'app.containers.SignUp.downloadSecretPhrase',
  },
  iAcceptPrivacyPolicy: {
    id: 'app.containers.SignUp.iAcceptPrivacyPolicy',
  },
  signUp: {
    id: 'app.containers.SignUp.signUp',
  },
  youHaveToSaveKeys: {
    id: 'app.containers.SignUp.youHaveToSaveKeys',
  },
  downloadKeys: {
    id: 'app.containers.SignUp.downloadKeys',
  },
  whyYouLikeUs: {
    id: 'app.containers.SignUp.whyYouLikeUs',
  },
  iHaveEosAccount: {
    id: 'app.containers.SignUp.iHaveEosAccount',
  },
  idontHaveEosAccount: {
    id: 'app.containers.SignUp.signUpViaEmailComplete',
  },
  passwordsDoNotMatch: {
    id: 'app.containers.SignUp.passwordsDoNotMatch',
  },
  signUpOptions: {
    id: 'app.containers.SignUp.signUpOptions',
  },
  peeranhaIsNotTypical: {
    id: 'app.containers.SignUp.peeranhaIsNotTypical',
  },
  telosBlockchainPowers: {
    id: 'app.containers.SignUp.telosBlockchainPowers',
  },
  weAreHappyToCover: {
    id: 'app.containers.SignUp.weAreHappyToCover',
  },
  ifYouLikeToSkip: {
    id: 'app.containers.SignUp.ifYouLikeToSkip',
  },
  or: {
    id: 'app.containers.SignUp.or',
  },
  doYouHaveAlreadyAccount: {
    id: 'app.containers.SignUp.doYouHaveAlreadyAccount',
  },
  youNeedEosAccount: {
    id: 'app.containers.SignUp.youNeedEosAccount',
  },
  theWayEosWorks: {
    id: 'app.containers.SignUp.theWayEosWorks',
  },
  ifYouCreateEos: {
    id: 'app.containers.SignUp.ifYouCreateEos',
  },
  checkYourEmail: {
    id: 'app.containers.SignUp.checkYourEmail',
  },
  almostDone: {
    id: 'app.containers.SignUp.almostDone',
  },
  firstParagraphAlmostDone: {
    id: 'app.containers.SignUp.firstParagraphAlmostDone',
  },
  secondParagraphAlmostDone: {
    id: 'app.containers.SignUp.secondParagraphAlmostDone',
  },
  thirdParagraphAlmostDone: {
    id: 'app.containers.SignUp.thirdParagraphAlmostDone',
  },
  weWillNotify: {
    id: 'app.containers.SignUp.weWillNotify',
  },
  goToMainPage: {
    id: 'app.containers.SignUp.goToMainPage',
  },
  [USER_ALREADY_REGISTERED_ERROR]: {
    id: 'app.containers.SignUp.userAlreadyRegistered',
  },
  [USER_REJECTED_SIGNATURE_REQUEST_ERROR]: {
    id: 'app.containers.SignUp.userRejectedSignatureRequest',
  },
  [USER_IS_NOT_SELECTED_ERROR]: {
    id: 'app.containers.SignUp.userIsNotSelected',
  },
  eosAccountNotFound: {
    id: 'app.containers.SignUp.eosAccountNotFound',
  },
  keysDoNotMatch: {
    id: 'app.containers.SignUp.keysDoNotMatch',
  },
  registrationWithEosAccountAlmostDone: {
    id: 'app.containers.SignUp.registrationWithEosAccountAlmostDone',
  },
  autogenerated: {
    id: 'app.containers.SignUp.autogenerated',
  },
  myOwn: {
    id: 'app.containers.SignUp.myOwn',
  },
  tgAccountID: {
    id: 'app.containers.SignUp.tgAccountID',
  },
  tgAccountName: {
    id: 'app.containers.SignUp.tgAccountName',
  },
  metaMaskIsNotInstalled: {
    id: 'app.containers.SignUp.metaMaskIsNotInstalled',
  },
});
