const PATH = 'app/Administration/';

export const ADD_MODERATOR_BUTTON_BUTTON =
  'app_Administration_ADD_MODERATOR_BUTTON';
export const OPEN_ADD_MODERATOR_FORM_BUTTON =
  'app_Administration_OPEN_ADD_MODERATOR_FORM_BUTTON';

export const WALLET_ADDRESS_FIELD = `${PATH}WALLET_ADDRESS_FIELD`;

export const GET_MODERATORS = `${PATH}GET_MODERATORS`;
export const GET_MODERATORS_SUCCESS = `${PATH}GET_MODERATORS_SUCCESS`;
export const GET_MODERATORS_ERROR = `${PATH}GET_MODERATORS_ERROR`;

export const ADD_MODERATOR = `${PATH}ADD_MODERATOR`;
export const ADD_MODERATOR_SUCCESS = `${PATH}ADD_MODERATOR_SUCCESS`;
export const ADD_MODERATOR_ERROR = `${PATH}ADD_MODERATOR_ERROR`;

export const REVOKE_MODERATOR = `${PATH}REVOKE_MODERATOR`;
export const REVOKE_MODERATOR_SUCCESS = `${PATH}REVOKE_MODERATOR_SUCCESS`;
export const REVOKE_MODERATOR_ERROR = `${PATH}REVOKE_MODERATOR_ERROR`;
