const PATH = 'app/Administration/';

export const ADD_MODERATOR_BUTTON_BUTTON =
  'app_Administration_ADD_MODERATOR_BUTTON';
export const OPEN_ADD_MODERATOR_FORM_BUTTON =
  'app_Administration_OPEN_ADD_MODERATOR_FORM_BUTTON';

export const WALLET_ADDRESS_FIELD = `${PATH}WALLET_ADDRESS_FIELD`;
export const ROLE_FIELD = `${PATH}ROLE_FIELD`;

export const GET_MODERATORS = `${PATH}GET_MODERATORS`;
export const GET_MODERATORS_SUCCESS = `${PATH}GET_MODERATORS_SUCCESS`;
export const GET_MODERATORS_ERROR = `${PATH}GET_MODERATORS_ERROR`;

export const ADD_ROLE = `${PATH}ADD_ROLE`;
export const ADD_ROLE_SUCCESS = `${PATH}ADD_ROLE_SUCCESS`;
export const ADD_ROLE_ERROR = `${PATH}ADD_ROLE_ERROR`;

export const REVOKE_ROLE = `${PATH}REVOKE_ROLE`;
export const REVOKE_ROLE_SUCCESS = `${PATH}REVOKE_ROLE_SUCCESS`;
export const REVOKE_ROLE_ERROR = `${PATH}REVOKE_ROLE_ERROR`;
