const base = 'app/containers/search';

const GET_RESULTS = `${base}/GET_RESULTS`;
const GET_RESULTS_SUCCESS = `${base}/GET_RESULTS_SUCCESS`;
const GET_RESULTS_ERROR = `${base}/GET_RESULTS_ERROR`;
const GET_EXISTING_QUESTIONS_SUCCESS = `${base}/GET_EXISTING_QUESTIONS_SUCCESS`;

export {
  GET_RESULTS,
  GET_RESULTS_SUCCESS,
  GET_RESULTS_ERROR,
  GET_EXISTING_QUESTIONS_SUCCESS,
};
