const PATH = 'app/CreateCommunity/';

export const FORM_NAME = `${PATH}FORM_NAME`;
export const FORM_TYPE = `${PATH}FORM_TYPE`;
export const CREATE_COMMUNITY_BUTTON =
  'app_CreateCommunity_CREATE_COMMUNITY_BUTTON';

export const LANGUAGE_FIELD = `${PATH}LANGUAGE_FIELD`;
export const COMM_AVATAR_FIELD = `${PATH}COMM_AVATAR_FIELD`;
export const COMM_NAME_FIELD = `${PATH}COMM_NAME_FIELD`;
export const COMM_SHORT_DESCRIPTION_FIELD = `${PATH}COMM_SHORT_DESCRIPTION_FIELD`;
export const ABOUT_FIELD = `${PATH}ABOUT_FIELD`;
export const COMM_MAIN_DESCRIPTION_FIELD = `${PATH}COMM_MAIN_DESCRIPTION_FIELD`;
export const COMM_OFFICIAL_SITE_FIELD = `${PATH}COMM_OFFICIAL_SITE_URL`;

export const TAG_NAME_FIELD = `${PATH}TAG_NAME_FIELD`;
export const TAG_DESCRIPTION_FIELD = `${PATH}TAG_DESCRIPTION_FIELD`;
export const TAG_SECTION = `${PATH}TAG_SECTION`;

export const REDIRECT_TO_CREATE_COMMUNITY = `${PATH}REDIRECT_TO_CREATE_COMMUNITY`;

export const CREATE_COMMUNITY = `${PATH}CREATE_COMMUNITY`;
export const CREATE_COMMUNITY_SUCCESS = `${PATH}/CREATE_COMMUNITY_SUCCESS`;
export const CREATE_COMMUNITY_ERROR = `${PATH}CREATE_COMMUNITY_ERROR`;

export const SET_DEFAULT_STORE = `${PATH}SET_DEFAULT_STORE`;

export const GET_FORM = `${PATH}GET_FORM`;
export const GET_FORM_PROCESSING = `${PATH}GET_FORM_PROCESSING`;
export const GET_FORM_SUCCESS = `${PATH}GET_FORM_SUCCESS`;
export const GET_FORM_ERROR = `${PATH}GET_FORM_ERROR`;

export const MIN_RATING_TO_CREATE_COMMUNITY = 500;
export const MIN_ENERGY_TO_CREATE_COMMUNITY = 125;

export const ANY_TYPE = 2;
export const GENERAL_TYPE = 1;
export const EXPERT_TYPE = 0;

export const STATE_KEY = 'createCommunity';
