import {
  PASSWORD_FIELD as PASSWORD_FIELD_SUGNUP,
  PASSWORD_CONFIRM_FIELD as PASSWORD_CONFIRM_FIELD_SUGNUP,
} from 'containers/SignUp/constants';

// Action types

const SEND_ANOTHER_CODE = 'containers/ForgotPassword/SEND_ANOTHER_CODE';

const SHOW_FORGOT_PASSWORD_MODAL =
  'containers/ForgotPassword/SHOW_FORGOT_PASSWORD_MODAL';
const HIDE_FORGOT_PASSWORD_MODAL =
  'containers/ForgotPassword/HIDE_FORGOT_PASSWORD_MODAL';

const GET_VERIFICATION_CODE = 'containers/ForgotPassword/GET_VERIFICATION_CODE';
const GET_VERIFICATION_CODE_SUCCESS =
  'containers/ForgotPassword/GET_VERIFICATION_CODE_SUCCESS';
const GET_VERIFICATION_CODE_ERROR =
  'containers/ForgotPassword/GET_VERIFICATION_CODE_ERROR';

const VERIFY_EMAIL = 'containers/ForgotPassword/VERIFY_EMAIL';
const VERIFY_EMAIL_SUCCESS = 'containers/ForgotPassword/VERIFY_EMAIL_SUCCESS';
const VERIFY_EMAIL_ERROR = 'containers/ForgotPassword/VERIFY_EMAIL_ERROR';

const CHANGE_PASSWORD = 'containers/ForgotPassword/CHANGE_PASSWORD';
const CHANGE_PASSWORD_SUCCESS =
  'containers/ForgotPassword/CHANGE_PASSWORD_SUCCESS';
const CHANGE_PASSWORD_ERROR = 'containers/ForgotPassword/CHANGE_PASSWORD_ERROR';

// Fields
const EMAIL_FIELD = 'email';
const VERIFICATION_CODE_FIELD = 'verificationCode';
const MASTER_KEY_FIELD = 'masterKey';

// Imported from SignUp because these constants are used to be validated by SignUp method @validatePassword
const PASSWORD_FIELD = PASSWORD_FIELD_SUGNUP;
const NEW_PASSWORD_FIELD = PASSWORD_CONFIRM_FIELD_SUGNUP;

// Content
const EMAIL_FORM = 'EMAIL_FORM';
const VERIFICATION_CODE_FORM = 'VERIFICATION_CODE_FORM';
const NEW_PASSWORD_FORM = 'NEW_PASSWORD_FORM';

export {
  EMAIL_FORM,
  VERIFICATION_CODE_FORM,
  NEW_PASSWORD_FORM,
  EMAIL_FIELD,
  VERIFICATION_CODE_FIELD,
  MASTER_KEY_FIELD,
  PASSWORD_FIELD,
  NEW_PASSWORD_FIELD,
  SHOW_FORGOT_PASSWORD_MODAL,
  HIDE_FORGOT_PASSWORD_MODAL,
  GET_VERIFICATION_CODE,
  GET_VERIFICATION_CODE_SUCCESS,
  GET_VERIFICATION_CODE_ERROR,
  VERIFY_EMAIL,
  VERIFY_EMAIL_SUCCESS,
  VERIFY_EMAIL_ERROR,
  CHANGE_PASSWORD,
  CHANGE_PASSWORD_SUCCESS,
  CHANGE_PASSWORD_ERROR,
  SEND_ANOTHER_CODE,
};
