export const GET_DOCUMENTATION = 'app/FAQ/GET_DOCUMENTATION';
export const GET_DOCUMENTATION_SUCCESS = 'app/FAQ/GET_DOCUMENTATION_SUCCESS';
export const GET_DOCUMENTATION_ERROR = 'app/FAQ/GET_DOCUMENTATION_ERROR';

export const TOGGLE_EDIT_DOCUMENTATION = 'app/TOGGLE_EDIT_DOCUMENTATION';
