export const GET_DOCUMENTATION = 'app/FAQ/GET_DOCUMENTATION';
export const GET_DOCUMENTATION_SUCCESS = 'app/FAQ/GET_DOCUMENTATION_SUCCESS';
export const GET_DOCUMENTATION_ERROR = 'app/FAQ/GET_DOCUMENTATION_ERROR';

export const TOGGLE_EDIT_DOCUMENTATION = 'app/TOGGLE_EDIT_DOCUMENTATION';
export const SET_EDIT_DOCUMENTATION = 'app/SET_EDIT_DOCUMENTATION';

export const SAVE_ARTICLE_TO_IPFS = 'app/SAVE_ARTICLE_TO_IPFS';
export const SAVE_ARTICLE_TO_IPFS_SUCCESS = 'app/SAVE_ARTICLE_TO_IPFS_SUCCESS';
export const SAVE_ARTICLE_TO_IPFS_FAILED = 'app/SAVE_ARTICLE_TO_IPFS_FAILED';
export const SAVE_MENU_DRAFT = 'app/SAVE_MENU_DRAFT';
export const VIEW_ARTICLE = 'app/VIEW_ARTICLE';
