const NAMESPACE = 'app/DOCUMENTATION/';

export const GET_ARTICLE = `${NAMESPACE}GET_ARTICLE`;
export const GET_ARTICLE_SUCCESS = `${NAMESPACE}GET_ARTICLE_SUCCESS`;
export const GET_ARTICLE_ERROR = `${NAMESPACE}GET_ARTICLE_ERROR`;

export const TOGGLE_EDIT_DOCUMENTATION = `${NAMESPACE}TOGGLE_EDIT_DOCUMENTATION`;
export const SET_VIEW_ARTICLE = `${NAMESPACE}SET_VIEW_ARTICLE`;
export const SET_EDIT_ARTICLE = `${NAMESPACE}SET_EDIT_ARTICLE`;
export const REMOVE_ARTICLE = `${NAMESPACE}REMOVE_ARTICLE`;

export const SAVE_MENU_DRAFT = `${NAMESPACE}SAVE_MENU_DRAFT`;

export const UPDATE_DOCUMENTATION_MENU = `${NAMESPACE}UPDATE_DOCUMENTATION_MENU`;
export const UPDATE_DOCUMENTATION_MENU_SUCCESS = `${NAMESPACE}UPDATE_DOCUMENTATION_MENU_SUCCESS`;
export const UPDATE_DOCUMENTATION_MENU_FAILED = `${NAMESPACE}UPDATE_DOCUMENTATION_MENU_FAILED`;

export const UPDATE_DOCUMENTATION_MENU_DRAFT = `${NAMESPACE}UPDATE_DOCUMENTATION_MENU_DRAFT`;

export const PINNED_ARTICLE = `${NAMESPACE}PINNED_ARTICLE`;
