const SECTION_ID = 'section_id';

const WHAT_IS_COMMUNITY_QUESTION = '3.0';
const WHO_MANAGES_COMMUNITY_QUESTION = '3.1';

const WHAT_IS_TAG_QUESTION = '4.0';
const HOW_TO_USE_IT_QUESTION = '4.1';

const WHY_I_HAVE_TO_WAIT_QUESTION = '5.0';
const WHEN_CAN_I_START_QUESTION = '5.1';
const WHAT_IS_EOS_ACCOUNT_FOR_QUESTION = '5.2';
const WHY_DO_I_NEES_THIS_SERVICE_QUESTION = '5.3';
const HOW_MUCH_DOES_IT_COST_QUESTION = '5.4';
const IS_THIS_WEBSITE_SAFE_QUESTION = '5.5';
const HOW_TO_USE_KEYS_QUESTION = '5.6';
const ALMOST_DONE_1ST_QUESTION = '5.7';
const ALMOST_DONE_2ST_QUESTION = '5.8';
const ALMOST_DONE_3ST_QUESTION = '5.9';

const HOW_TO_ASK_QUESTION = '6.0';
const HOW_TO_FORMAT_QUESTION = '6.1';
const HOW_TO_TAG_QUESTION = '6.2';

export {
  SECTION_ID,
  WHY_I_HAVE_TO_WAIT_QUESTION,
  WHEN_CAN_I_START_QUESTION,
  WHAT_IS_EOS_ACCOUNT_FOR_QUESTION,
  WHY_DO_I_NEES_THIS_SERVICE_QUESTION,
  HOW_MUCH_DOES_IT_COST_QUESTION,
  IS_THIS_WEBSITE_SAFE_QUESTION,
  HOW_TO_USE_KEYS_QUESTION,
  ALMOST_DONE_1ST_QUESTION,
  ALMOST_DONE_2ST_QUESTION,
  ALMOST_DONE_3ST_QUESTION,
  HOW_TO_ASK_QUESTION,
  HOW_TO_FORMAT_QUESTION,
  HOW_TO_TAG_QUESTION,
  WHAT_IS_COMMUNITY_QUESTION,
  WHO_MANAGES_COMMUNITY_QUESTION,
  WHAT_IS_TAG_QUESTION,
  HOW_TO_USE_IT_QUESTION,
};
