const SECTION_ID = 'section_id';

const HOW_STORE_MY_KEYS_QUESTION = '1.0';
const CAN_SIGN_UP_WITH_EAMIL_IF_HAVE_TELOS_ACCT_QUESTION = '1.1';
const CAN_I_DELETE_ACCOUNT_QUESTION = '1.2';
const WHAT_IS_MASTER_KEY_QUESTION = '1.3';

const ALMOST_DONE_1ST_QUESTION = '1.0';
const ALMOST_DONE_2ST_QUESTION = '1.1';
const ALMOST_DONE_3ST_QUESTION = '1.2';

// Questions currently do not exist
const WHAT_IS_ENERGY = '0.0';
const HOW_TO_CHARGE = '0.1';
const VALUE_OF_ACTIONS = '0.2';

const WHAT_IS_COMMUNITY_QUESTION = '2.0';
const WHO_MANAGES_COMMUNITY_QUESTION = '2.1';

const WHAT_IS_TAG_QUESTION = '2.0';
const HOW_TO_USE_IT_QUESTION = '2.1';

const HOW_TO_ASK_QUESTION = '3.0';
const HOW_TO_FORMAT_QUESTION = '3.1';
const HOW_TO_TAG_QUESTION = '3.2';

const ABOUT_PEERANHA_SECTION = '0';

const WHAT_IS_PEERANHA = '0.0';
const HOT_IT_DIFF = '0.1';
const HOW_IT_WORKS = '0.2';
const WHERE_TOKENS_COME_FROM = '0.3';
const VALUE_OF_TOKEN = '0.5';

const SUPERPOWER_SECTION = '8';
const WHAT_IS_SUPERPOWER = '8.0';
const HOW_TO_MAKE_A_BET = '8.1';
const HOW_TO_MAKE_A_BET_AUTOMATICALLY = '8.2';
const WHY_ARE_MY_TOKENS_LOCKED = '8.3';
const WHEN_I_CAN_GET_MY_REWARD = '8.4';

export {
  SECTION_ID,
  ABOUT_PEERANHA_SECTION,
  HOW_STORE_MY_KEYS_QUESTION,
  CAN_SIGN_UP_WITH_EAMIL_IF_HAVE_TELOS_ACCT_QUESTION,
  CAN_I_DELETE_ACCOUNT_QUESTION,
  WHAT_IS_MASTER_KEY_QUESTION,
  ALMOST_DONE_1ST_QUESTION,
  ALMOST_DONE_2ST_QUESTION,
  ALMOST_DONE_3ST_QUESTION,
  HOW_TO_ASK_QUESTION,
  HOW_TO_FORMAT_QUESTION,
  HOW_TO_TAG_QUESTION,
  WHAT_IS_COMMUNITY_QUESTION,
  WHO_MANAGES_COMMUNITY_QUESTION,
  WHAT_IS_TAG_QUESTION,
  HOW_TO_USE_IT_QUESTION,
  WHAT_IS_PEERANHA,
  HOT_IT_DIFF,
  HOW_IT_WORKS,
  WHERE_TOKENS_COME_FROM,
  VALUE_OF_TOKEN,
  WHAT_IS_ENERGY,
  HOW_TO_CHARGE,
  VALUE_OF_ACTIONS,
  SUPERPOWER_SECTION,
  WHAT_IS_SUPERPOWER,
  HOW_TO_MAKE_A_BET,
  HOW_TO_MAKE_A_BET_AUTOMATICALLY,
  WHY_ARE_MY_TOKENS_LOCKED,
  WHEN_I_CAN_GET_MY_REWARD,
};
