export const GO_TO_CREATE_COMMUNITY_SCREEN_BUTTON_ID =
  'app_Communities_GO_TO_CREATE_COMMUNITY_SCREEN_BUTTON_ID';

export const SUBCOMMUNITIES_ID_ARRAY = [];

export const HIDDEN_COMMUNITIES_ID = [];
