/*
 *
 * Communities constants
 *
 */
const PATH = 'app/Communities/';

export const GO_TO_CREATE_COMMUNITY_SCREEN_BUTTON_ID =
  'app_Communities_GO_TO_CREATE_COMMUNITY_SCREEN_BUTTON_ID';

export const GET_SUGGESTED_COMMUNITIES = `${PATH}GET_SUGGESTED_COMMUNITIES`;
export const GET_SUGGESTED_COMMUNITIES_SUCCESS = `${PATH}GET_SUGGESTED_COMMUNITIES_SUCCESS`;
export const GET_SUGGESTED_COMMUNITIES_ERROR = `${PATH}GET_SUGGESTED_COMMUNITIES_ERROR`;
