const PATH = 'app/containers/AppWrapper';

export const LEFT_MENU_WIDTH = 200;
export const SHOW_LEFT_MENU = `${PATH}/SHOW_LEFT_MENU`;
export const HIDE_LEFT_MENU = `${PATH}/HIDE_LEFT_MENU`;

export const GET_DOCUMENTATION_MENU = `${PATH}/GET_DOCUMENTATION_MENU`;
export const GET_DOCUMENTATION_MENU_SUCCESS = `${PATH}/GET_DOCUMENTATION_MENU_SUCCESS`;
export const GET_DOCUMENTATION_MENU_ERROR = `${PATH}/GET_DOCUMENTATION_MENU_ERROR`;
