/*
 *
 * Profile constants
 *
 */

export const GET_PROFILE_INFORMATION = 'app/Profile/GET_PROFILE_INFORMATION';
export const GET_PROFILE_INFORMATION_SUCCESS =
  'app/Profile/GET_PROFILE_INFORMATION_SUCCESS';
export const GET_PROFILE_INFORMATION_ERROR =
  'app/Profile/GET_PROFILE_INFORMATION_ERROR';

export const UPLOAD_IMAGE_FILE = 'app/Profile/UPLOAD_IMAGE_FILE';
export const UPLOAD_IMAGE_FILE_SUCCESS =
  'app/Profile/UPLOAD_IMAGE_FILE_SUCCESS';
export const UPLOAD_IMAGE_FILE_ERROR = 'app/Profile/UPLOAD_IMAGE_FILE_ERROR';
