export const GET_EXISTING_TAGS = 'app/Tags/GET_EXISTING_TAGS';
export const GET_EXISTING_TAGS_SUCCESS = 'app/Tags/GET_EXISTING_TAGS_SUCCESS';
export const GET_EXISTING_TAGS_ERROR = 'app/Tags/GET_EXISTING_TAGS_ERROR';

export const GO_TO_CREATE_TAG_SCREEN_BUTTON_ID =
  'app_containers_GO_TO_CREATE_TAG_SCREEN_BUTTON_ID';
