const PATH = `app/QuestionsOfUser`;

export const GET_QUESTIONS = `${PATH}/GET_QUESTIONS`;
export const GET_QUESTIONS_SUCCESS = `${PATH}/GET_QUESTIONS_SUCCESS`;
export const GET_QUESTIONS_ERROR = `${PATH}/GET_QUESTIONS_ERROR`;
