export const GET_SEARCH_RESULT = 'app/AISearch/GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'app/AISearch/GET_SEARCH_RESULT_SUCCESS';
export const GET_CHUNK_SUCCESS = 'app/AISearch/GET_CHUNK_SUCCESS';
export const STOP_GENERATION = 'app/AISearch/STOP_GENERATION';
export const START_OVER = 'app/AISearch/START_OVER';
export const GET_SEARCH_RESULT_ERROR = 'app/AISearch/GET_SEARCH_RESULT_ERROR';
