export const GET_SEARCH_RESULT = 'app/AISearch/GET_SEARCH_RESULT';
export const GET_SEARCH_RESULT_SUCCESS = 'app/AISearch/GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_ERROR = 'app/AISearch/GET_SEARCH_RESULT_ERROR';
