/*
 *
 * EditQuestion constants
 *
 */

const GET_ASKED_QUESTION = 'app/EditQuestion/GET_ASKED_QUESTION';
const GET_ASKED_QUESTION_SUCCESS =
  'app/EditQuestion/GET_ASKED_QUESTION_SUCCESS';
const GET_ASKED_QUESTION_ERROR = 'app/EditQuestion/GET_ASKED_QUESTION_ERROR';

const EDIT_QUESTION_FORM = 'app/AskQuestion/EDIT_QUESTION_FORM';
const EDIT_QUESTION_BUTTON = 'app_AskQuestion_EDIT_QUESTION_BUTTON';

const EDIT_QUESTION = 'app/EditQuestion/EDIT_QUESTION';
const EDIT_QUESTION_SUCCESS = 'app/EditQuestion/EDIT_QUESTION_SUCCESS';
const EDIT_QUESTION_ERROR = 'app/EditQuestion/EDIT_QUESTION_ERROR';

const REDIRECT_TO_EDIT_QUESTION_PAGE =
  'app/EditQuestion/REDIRECT_TO_EDIT_QUESTION_PAGE';

const MIN_RATING_TO_EDIT_QUESTION = 0;
const MIN_ENERGY_TO_EDIT_QUESTION = 2;

export {
  GET_ASKED_QUESTION,
  GET_ASKED_QUESTION_SUCCESS,
  GET_ASKED_QUESTION_ERROR,
  EDIT_QUESTION_FORM,
  EDIT_QUESTION_BUTTON,
  EDIT_QUESTION,
  EDIT_QUESTION_SUCCESS,
  EDIT_QUESTION_ERROR,
  MIN_RATING_TO_EDIT_QUESTION,
  MIN_ENERGY_TO_EDIT_QUESTION,
  REDIRECT_TO_EDIT_QUESTION_PAGE,
};
